### ISSUE TITLE
Assignment 1: Ready for Grading!

### ISSUE THREAD

**Issue by mcasey24** [SES-5215-F2020/mcasey-quant#1]
the .rmd, .html, and .csv files are ready under the commit "Assignment 1 Final"

**Comment by saratepfer** [comment]
Great job on this assignment!

**Comments on Code**
In line 90, when you are selecting variables, it looks like BLD_label was selected instead of your variable num_units. You can either drop line 80 or adjust it to say num_units = BLD_label, and then select num_units instead of BLD_label in line 90. The latter option is a little clearer for the reader (because the reader doesn't need to know what BLD_label means).
